name: "Celio Rodrigues"
username: "@cemanuelio"
role: "Fullstack developer"
picture: "http://i66.tinypic.com/6supnb.jpg"
facebook: "https://www.facebook.com/cemanuelio"
twitter: "https://twitter.com/cemanuelio"
instagram: "https://www.instagram.com/cemanuelio/"
linkedin: "https://www.linkedin.com/in/rodriguescelio/"
github: "https://github.com/rodriguescelio"
about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi efficitur in neque sit amet dapibus. Nulla est lorem, faucibus eget euismod id, varius ut dolor. <a href="#">Nullam varius</a> auctor justo, nec lacinia libero eleifend sit amet. Suspendisse sagittis diam id erat ultricies malesuada. Morbi scelerisque sodales libero ut iaculis. Aenean vitae nisl aliquet, eleifend justo vel, lacinia sem. Praesent ut leo nec quam facilisis lacinia. Sed luctus hendrerit velit et sagittis. Donec molestie porttitor urna nec ullamcorper.'